# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
title: ThermalGaussian
description: Rongfeng Lu1,3,∗,† Hangyu Chen1,∗ Zunjie Zhu1,3 Yuhang Qin1 Ming Lu2 Le Zhang1 Chenggang Yan 1 Anke Xue1,†
github:
  is_project_page: false

