# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
title: ThermalGaussian
description: "Rongfeng Lu<sup>1</sup>, Hangyu Chen, Zunjie Zhu, Yuhang Qin, Ming Lu, Le Zhang, Chenggang Yan, Anke Xue <br> Hangzhou Dianzi University ,Intel Labs China ,Lishui Institute of Hangzhou Dianzi University"
is_project_page: false

