# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
title: ThermalGaussian
description: The official examples of article "THERMALGAUSSIAN : THERMAL 3D GAUSSIAN SPLATTING"
github:
  is_project_page: false

